### ISSUE TITLE
How to exclude packages?

### ISSUE THREAD

**Issue by rafaelmotta** [bndkt/react-native-app-clip#14]
hey.. I'm trying to set up `excludedPackages` option, however, it looks like isn't excluding. Am I doing something wrong?

<img width="399" alt="Screenshot 2023-04-27 at 11 52 09" src="https://user-images.githubusercontent.com/446731/234901081-066f4d71-ba38-43a7-95ee-2f3124dfd7ac.png">

**Comment by bndkt** [comment]
Please note that only the native part will be excluded (so this doesn't affect size of bundle.js yet) and they will only be excluded for the App Clip target. How do you determine that the exclusion didn't work?
