### ISSUE TITLE
Question about the bundle identifier

### ISSUE THREAD

**Issue by nandorojo** [bndkt/react-native-app-clip#2]
First off, wow! I've been wanting this for so long. So excited to try it.

Question: I use react-native-firebase in my app. As part of the setup on Firebase's website, I need to tell it my bundle identifier. 

How would this work with the app clips? Does the app clip have a separate bundle identifier, or do you think firebase would still work it the identifier of the main app?

Thanks so much!

**Comment by EvanBacon** [comment]
App clips use a ["bundle identifier suffix"](https://stackoverflow.com/questions/3436260/bundle-id-suffix-what-is-it) this extends the default app bundle identifier.

**Comment by nandorojo** [comment]
The updated setup is soo clean 🔥
