### ISSUE TITLE
JS bundles

### ISSUE THREAD

**Issue by KrastanD** [bndkt/react-native-app-clip#21]
Just want to make sure I'm understanding things correctly. This reuses the same js bundle for both the main app and the clip? Is this a limitation for expo?  Being able to use separate bundles would dramatically decrease the bundle size, no?

**Comment by KrastanD** [comment]
Related to this, when I try to archive the app to see it's size, I keep getting an error that `...Clip.app/main.jsbundle does not exist`. Any clue what I have to change to get this to work?

**Comment by nahn20** [comment]
Yep, you are correct! By default, your app clip uses the same JS bundle as your main app. I've done some experiments with different entry files but I've found in practice, you'll be sacrificing significant amounts of code re-use. My suggestion is using a special file extension for app clip files, as implemented in #42. If you have any hefty components, you can just include a blank `*.clip.ts` file to exclude them from the app clip build (similar to how one would for [platform-specific files](https://reactnative.dev/docs/0.73/platform-specific-code#native-specific-extensions-ie-sharing-code-with-nodejs-and-web)).

**Comment by nathan-ahn** [comment]
Support for the `*.clip.ts` extension has been added in `v0.5.0`! You can now have separate entrypoints (or any nested files) for the main app and the App Clip, so you can choose to share as much logic as you want at any point in the hierarchy. This includes completely separate the two bundles.
