### ISSUE TITLE
Build fails due to mismatch in tablet configuration

### ISSUE THREAD

**Issue by nathan-ahn** [bndkt/react-native-app-clip#24]
# Detection
EAS build failing due to `error: The UIDeviceFamily of an App Clip ('[1]') must be equal to the UIDeviceFamily of its containing parent app ('[1, 2]').`. After manually building and viewing in Xcode, the main app target supports iPhone, iPad, and Mac while the app clip supports only iPhone and Mac. 

# Minimum Reproducible Example
- Init using `create-expo-app` version 2.1.1
- Install `react-native-app-clip` version 0.2.4
- Modify `react-native-app-clip` plugin config to include a name (likely irrelevant, but might be messing with the plugin config defaults)
- Fix from #23 

# Temporary Fix
Remove tablet support from the main app (`supportsTablet: false`). For obvious reasons, not an ideal fix. I'm sure one could better fix this by manually adding tablet support in the app clip's `Info.plist`. 

# Suggested Fix
Conditionally add iPad as a supported destination based on the value of `supportsTablet`.

**Comment by glburgess** [comment]
Is there a way to make react-native-app-clip `supportsTablet: true` and not fail building? 

The original app I'm trying to make a clip for supported tablets and Apple will not let an app drop support for tablets if it had supported it at one point so I cannot submit if supportsTablet is false and I cannot build if supportsTablet is true.

**Comment by nahn20** [comment]
#46 should fix this issue!

**Comment by nathan-ahn** [comment]
Fixed in #50.
