### ISSUE TITLE
`excludedPackages` doesn't work

### ISSUE THREAD

**Issue by nathan-ahn** [bndkt/react-native-app-clip#27]
## Findings
I ran two tests to determine that `excludedPackages` isn't working. Both using [react-native-skia](https://shopify.github.io/react-native-skia/) which is known to have a [significant iOS bundle size of ~5.8 MB](https://shopify.github.io/react-native-skia/docs/getting-started/bundle-size). Resulting bundle sizes are determined using `App Thinning Size Report.txt` as [recommend by Apple](https://developer.apple.com/documentation/app_clips/creating_an_app_clip_with_xcode). 

### Test 1
Including "@shopify/react-native-skia" in `excludedPackages` yields an uncompressed size of 27.7 MB. 
Removing it yields the same uncompressed size of 27.7 MB

### Test 2
As in the previous test, including `"@shopify/react-native-skia"` in `excludedPackages` yields an uncompressed size of 27.7 MB. 
I uninstall `@shopify/react-native-skia` completely and got an uncompressed bundle size of 21.8 MB. According to Shopify, the JavaScript bundle is only supposed to account for 220 KB (and likely 0 KB in our case given that it was never imported). So the size discrepancy is almost definitely due to properly removed native code. 

#### Additional Note
`ios/Pods/Podfile` generates correctly with `"@shopify/react-native-skia"` being included in `exclude`.

**Comment by david-arteaga** [comment]
btw I've tested with `v0.1.4` and `excludedPackages` does work as expected.
I archived a build without any packages in that list -- got about 55MB
Then added a bunch of packages in our project to `excludedPackages`, archived again -- got about 26MB

So the issue may have been introduced after `v0.1.4`

**Comment by nahn20** [comment]
Going to experiment, but I think there's a good chance this issue is related to [this commit](https://github.com/bndkt/react-native-app-clip/commit/7487d249abdf6f55316144ac53c10a34f21cae6b).

**Comment by nahn20** [comment]
No success :/
I undid the above-linked commit and had success in running the build, but it didn't lead to any decrease in app clip size. If anyone wants to try it out for themselves, [here's the changes you need to make](https://github.com/nahn20/react-native-app-clip/tree/%40nahn20/excluded-packages-fix).

**Comment by nathan-ahn** [comment]
This issue only affects non-Expo modules. Expo modules are correctly handled with `use_expo_modules`'s `exclude` field, but non-Expo modules are going to require a custom implementation.

**Comment by nathan-ahn** [comment]
Fixed in #50.
