### ISSUE TITLE
cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by innoware-mx** [bndkt/react-native-app-clip#29]
I followed the most simple recipe:

`https://bndkt.com/blog/2022/tutorial-react-native-app-clip`

An error is thrown when executing eas build:configure:

`TypeError: Cannot read properties of undefined (reading 'name')
    at withAppClip (clipper\node_modules\react-native-app-clip\plugin\build\index.js:9:32)`

Expected behaviour:

It runs eas build:configure without error

**Comment by Lurtroxx** [comment]
You are missing the "name" config in app.config... It does not add it automatically when you install the package.

<img width="560" alt="image" src="https://github.com/bndkt/react-native-app-clip/assets/32040179/dd2add21-3556-4e8d-bd2f-ae80b533a959">

**Comment by danielafcarey** [comment]
@innoware-mx did that solution work for you? I was still getting this error when I added the "name" in my app.config. I added some more config ([found here](https://reactnativeexample.com/expo-config-plugin-that-generates-an-app-clip-for-ios-apps-built-with-expo/)) to specify the target name and other options and then it worked.

**Comment by bndkt** [comment]
Should be fixed with https://github.com/bndkt/react-native-app-clip/releases/tag/v0.3.0
