### ISSUE TITLE
Build fails with "The relationship 'parentBundleId' is required but was not provided with this request" when using this package

### ISSUE THREAD

**Issue by szpasztor** [bndkt/react-native-app-clip#32]
A configuration issue seems to break all release builds when the latest version of this package is used with EAS build. I've filed a fully detailed ticket [here](https://github.com/expo/eas-cli/issues/2262), including reproduction steps – which is essentially just setting up this library. I wanted to file an issue here as well, as the root may be "react-native-app-clip" not EAS (the error message was unclear, so I've filed to both libraries).

**Comment by nathan-ahn** [comment]
Clarified docs in #50 based on [suggestion](https://github.com/expo/eas-cli/issues/2262#issuecomment-2095800263) in linked ticket.
