### ISSUE TITLE
Native app clip?

### ISSUE THREAD

**Issue by djMax** [bndkt/react-native-app-clip#34]
Our app is complex enough that I don't think sharing code is useful - i.e. I'd rather just write the app clip in swift. BUT, it sure would be nice to be able to use Expo as is for the main app and bundle the app clip "as usual" for an app. Does this even make any sense? I imagine maybe it's an entirely different plugin, but would the plugin approach still work? Or perhaps it should just be an entirely separate project?

**Comment by bndkt** [comment]
I think for this approach https://github.com/EvanBacon/expo-apple-targets would be suitable.
