### ISSUE TITLE
App Clip works on IOS 17.0 but NOT WORKING on 17.4!!!!

### ISSUE THREAD

**Issue by darthgween** [bndkt/react-native-app-clip#36]
On simulator IOS 17.0 I run npx expo run:ios and the app builds and is opened correctly
Then I run npx expo run:ios --scheme and select myappClip and the App Clip runs correctly

The same on IOS 17.4 doesnt work, when i run npx expo run:ios --scheme it opens the full app

Please help!!!

**Comment by hamam99** [comment]
same issue, cant work in IOS 17.4

**Comment by archetype2142** [comment]
+1

**Comment by oliverloops** [comment]
Hello guys, can you reproduce the error or show an screenshot or the error?

**Comment by manlio16** [comment]
same issue here

**Comment by haileyok** [comment]
@darthgween Had to deal with this recently, see https://github.com/bndkt/react-native-app-clip/pull/38/commits/2313633df0951d9578df579cbed4b9ec876cf803

**Comment by bndkt** [comment]
Should be fixed with https://github.com/bndkt/react-native-app-clip/releases/tag/v0.3.0
