### ISSUE TITLE
App Clip Not Installed in iOS 17.5

### ISSUE THREAD

**Issue by MisterCommand** [bndkt/react-native-app-clip#41]
After running `expo run:ios` and `expo run:ios --scheme` in the example application provided, the app clip does not appear on the home screen.

**Comment by vishaljak** [comment]
having the same issue

**Comment by artem-alek** [comment]
I thought i was doing something wrong...same here...the clip doesnt load or get added. no build issues

**Comment by nahn20** [comment]
I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.

**Comment by vishaljak** [comment]
can you list the steps for the workaround please? @nahn20

**Comment by nahn20** [comment]
> can you list the steps for the workaround please? @nahn20

1. Open the app clip in the iOS Simulator
2. In the Simulator menu: Device -> Erase All Content and Settings

In theory you could also wipe your real device, but I don't think that's a feasible solution. I'd only recommend using a throwaway Simulator.

**Comment by artem-alek** [comment]
> I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.

are you saying that when i run npx expo run:ios and it installs the full app on the simulator, i have to 

1. Delete the real app from the simulator
2. run npx expo run:ios --schema (select app clip) 

this then will work?

**Comment by nahn20** [comment]
> > I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.
> 
> are you saying that when i run npx expo run:ios and it installs the full app on the simulator, i have to
> 
>     1. Delete the real app from the simulator
> 
>     2. run npx expo run:ios --schema (select app clip)
> 
> 
> this then will work?

I'm saying that whenever you install the full app on the simulator you have to erase all the data from the simulator to get it working again. It's not an elegant solution, but it only takes a few seconds and means that you can test app clip again on a fresh device.

**Comment by artem-alek** [comment]
> > > I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.
> > 
> > 
> > are you saying that when i run npx expo run:ios and it installs the full app on the simulator, i have to
> > ```
> > 1. Delete the real app from the simulator
> > 
> > 2. run npx expo run:ios --schema (select app clip)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this then will work?
> 
> I'm saying that whenever you install the full app on the simulator you have to erase all the data from the simulator to get it working again. It's not an elegant solution, but it only takes a few seconds and means that you can test app clip again on a fresh device.

I cant get the app clip to work at all. 

When i erase all contents and then run npx expo run:ios --schema appClip 

I get an error where the URL is not found. 

CommandError: Device has no app to handle the URI: .......://expo-development-client/?url=http%3A%2F%2F192.168.182.209%3A8081

**Comment by nahn20** [comment]
> > > > I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.
> > > 
> > > 
> > > are you saying that when i run npx expo run:ios and it installs the full app on the simulator, i have to
> > > ```
> > > 1. Delete the real app from the simulator
> > > 
> > > 2. run npx expo run:ios --schema (select app clip)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > this then will work?
> > 
> > 
> > I'm saying that whenever you install the full app on the simulator you have to erase all the data from the simulator to get it working again. It's not an elegant solution, but it only takes a few seconds and means that you can test app clip again on a fresh device.
> 
> I cant get the app clip to work at all.
> 
> When i erase all contents and then run npx expo run:ios --schema appClip
> 
> I get an error where the URL is not found.
> 
> CommandError: Device has no app to handle the URI: .......://expo-development-client/?url=http%3A%2F%2F192.168.182.209%3A8081

That's because Expo is trying to open your main app, not the app clip. I get this issue every time too. It's slightly less convenient, but you can just open the app manually.

**Comment by artem-alek** [comment]
> > > > > I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.
> > > > 
> > > > 
> > > > are you saying that when i run npx expo run:ios and it installs the full app on the simulator, i have to
> > > > ```
> > > > 1. Delete the real app from the simulator
> > > > 
> > > > 2. run npx expo run:ios --schema (select app clip)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > this then will work?
> > > 
> > > 
> > > I'm saying that whenever you install the full app on the simulator you have to erase all the data from the simulator to get it working again. It's not an elegant solution, but it only takes a few seconds and means that you can test app clip again on a fresh device.
> > 
> > 
> > I cant get the app clip to work at all.
> > When i erase all contents and then run npx expo run:ios --schema appClip
> > I get an error where the URL is not found.
> > CommandError: Device has no app to handle the URI: .......://expo-development-client/?url=http%3A%2F%2F192.168.182.209%3A8081
> 
> That's because Expo is trying to open your main app, not the app clip. I get this issue every time too. It's slightly less convenient, but you can just open the app manually.

Im not a big expert on how to do that manually? I run npx expo run:ios --schema clipApp and it loads with not problem but then it opens the main app and isClip() is always false. I am using tabs as my root as well.

**Comment by nahn20** [comment]
> > > > > > I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.
> > > > > 
> > > > > 
> > > > > are you saying that when i run npx expo run:ios and it installs the full app on the simulator, i have to
> > > > > ```
> > > > > 1. Delete the real app from the simulator
> > > > > 
> > > > > 2. run npx expo run:ios --schema (select app clip)
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > this then will work?
> > > > 
> > > > 
> > > > I'm saying that whenever you install the full app on the simulator you have to erase all the data from the simulator to get it working again. It's not an elegant solution, but it only takes a few seconds and means that you can test app clip again on a fresh device.
> > > 
> > > 
> > > I cant get the app clip to work at all.
> > > When i erase all contents and then run npx expo run:ios --schema appClip
> > > I get an error where the URL is not found.
> > > CommandError: Device has no app to handle the URI: .......://expo-development-client/?url=http%3A%2F%2F192.168.182.209%3A8081
> > 
> > 
> > That's because Expo is trying to open your main app, not the app clip. I get this issue every time too. It's slightly less convenient, but you can just open the app manually.
> 
> Im not a big expert on how to do that manually? I run npx expo run:ios --schema clipApp and it loads with not problem but then it opens the main app and isClip() is always false. I am using tabs as my root as well.

App clips don't currently open automatically. You need it to show up on your home screen (which is what this issue thread is for!). Once it shows up on your home screen, you can just click on it to run your app clip. 

If your app clip is not showing up on your home screen in 17.5, it's likely because you previously installed the main app. In this case, you can solve the issue by starting with a fresh device (I would recommend running app clip in simulator and using Device -> Erase All Content and Settings whenever this issue happens). Deleting the main app does not fix this issue. You need to restart with a fresh device that has no memory of the main app ever being installed.

As far as I can tell, this is not an issue in TestFlight. Once I've tested the app clip in simulator (where I can comfortably erase all content), I then create a TestFlight build to test on a real device.

**Comment by artem-alek** [comment]
> > > > > > > I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.
> > > > > > 
> > > > > > 
> > > > > > are you saying that when i run npx expo run:ios and it installs the full app on the simulator, i have to
> > > > > > ```
> > > > > > 1. Delete the real app from the simulator
> > > > > > 
> > > > > > 2. run npx expo run:ios --schema (select app clip)
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > this then will work?
> > > > > 
> > > > > 
> > > > > I'm saying that whenever you install the full app on the simulator you have to erase all the data from the simulator to get it working again. It's not an elegant solution, but it only takes a few seconds and means that you can test app clip again on a fresh device.
> > > > 
> > > > 
> > > > I cant get the app clip to work at all.
> > > > When i erase all contents and then run npx expo run:ios --schema appClip
> > > > I get an error where the URL is not found.
> > > > CommandError: Device has no app to handle the URI: .......://expo-development-client/?url=http%3A%2F%2F192.168.182.209%3A8081
> > > 
> > > 
> > > That's because Expo is trying to open your main app, not the app clip. I get this issue every time too. It's slightly less convenient, but you can just open the app manually.
> > 
> > 
> > Im not a big expert on how to do that manually? I run npx expo run:ios --schema clipApp and it loads with not problem but then it opens the main app and isClip() is always false. I am using tabs as my root as well.
> 
> App clips don't currently open automatically. You need it to show up on your home screen (which is what this issue thread is for!). Once it shows up on your home screen, you can just click on it to run your app clip.
> 
> If your app clip is not showing up on your home screen in 17.5, it's likely because you previously installed the main app. In this case, you can solve the issue by starting with a fresh device (I would recommend running app clip in simulator and using Device -> Erase All Content and Settings whenever this issue happens). Deleting the main app does not fix this issue. You need to restart with a fresh device that has no memory of the main app ever being installed.
> 
> As far as I can tell, this is not an issue in TestFlight. Once I've tested the app clip in simulator (where I can comfortably erase all content), I then create a TestFlight build to test on a real device.

Thank you for a detailed explanation. I remember seeing a app clip on my simulator once then never again after i deleted it and its been days of attempts to make it work. I will try your method.

**Comment by artem-alek** [comment]
> > > > > > > > I've found that this happens after installing the real app. I've been working around this issue by wiping the device, but that's only a feasible solution when developing using the simulator.
> > > > > > > 
> > > > > > > 
> > > > > > > are you saying that when i run npx expo run:ios and it installs the full app on the simulator, i have to
> > > > > > > ```
> > > > > > > 1. Delete the real app from the simulator
> > > > > > > 
> > > > > > > 2. run npx expo run:ios --schema (select app clip)
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > this then will work?
> > > > > > 
> > > > > > 
> > > > > > I'm saying that whenever you install the full app on the simulator you have to erase all the data from the simulator to get it working again. It's not an elegant solution, but it only takes a few seconds and means that you can test app clip again on a fresh device.
> > > > > 
> > > > > 
> > > > > I cant get the app clip to work at all.
> > > > > When i erase all contents and then run npx expo run:ios --schema appClip
> > > > > I get an error where the URL is not found.
> > > > > CommandError: Device has no app to handle the URI: .......://expo-development-client/?url=http%3A%2F%2F192.168.182.209%3A8081
> > > > 
> > > > 
> > > > That's because Expo is trying to open your main app, not the app clip. I get this issue every time too. It's slightly less convenient, but you can just open the app manually.
> > > 
> > > 
> > > Im not a big expert on how to do that manually? I run npx expo run:ios --schema clipApp and it loads with not problem but then it opens the main app and isClip() is always false. I am using tabs as my root as well.
> > 
> > 
> > App clips don't currently open automatically. You need it to show up on your home screen (which is what this issue thread is for!). Once it shows up on your home screen, you can just click on it to run your app clip.
> > If your app clip is not showing up on your home screen in 17.5, it's likely because you previously installed the main app. In this case, you can solve the issue by starting with a fresh device (I would recommend running app clip in simulator and using Device -> Erase All Content and Settings whenever this issue happens). Deleting the main app does not fix this issue. You need to restart with a fresh device that has no memory of the main app ever being installed.
> > As far as I can tell, this is not an issue in TestFlight. Once I've tested the app clip in simulator (where I can comfortably erase all content), I then create a TestFlight build to test on a real device.
> 
> Thank you for a detailed explanation. I remember seeing a app clip on my simulator once then never again after i deleted it and its been days of attempts to make it work. I will try your method.

My biggest problem is i cant see the clip installed on the device even after restart. but I am not using dev-client but just run:ios on simulator.

**Comment by artem-alek** [comment]
any fix for this any time soon?

**Comment by axelv71** [comment]
I have the same problem as you, I can't see the App Clip on the home page. However, I can see it in Settings>App Extract. But I can't launch it.

Has anyone figured out how to solve this bug?

**Comment by vishaljak** [comment]
It was not working on the simulator but I got it to work on a real device.

Just double check the invocation link for the app clip from your phone's developer settings (local experiences)

**Comment by bndkt** [comment]
Hello all, sorry I didn't have time to focus on this library in the past weeks. I'm just catching up now. Can confirm that I have the same problem and even wiping the Simulator device doesn't help. I also notices that in a 17.5 simulator, the "Local Experience" menu within developer settings is gone, which is Apple's recommended way of testing App Clips (https://developer.apple.com/documentation/appclip/testing-the-launch-experience-of-your-app-clip#Test-invocations-with-a-local-experience).

I'll continue to investigate but am inclined to wait until iOS 18 is out on Monday and then see how it goes with the new Simulator, as Apple keeps changing things ...

**Comment by pandeiro** [comment]
Did this begin working again in iOS 18?

**Comment by nathan-ahn** [comment]
Appears to still be broken in iOS 18.1.

**Comment by nathan-ahn** [comment]
I'm beginning to believe this is an Apple bug. Even on TestFlight, an installed App Clip does not show up in the app library and search. This isn't an issue since you can just click "Test" and "Open" within TestFlight, but for development installations there's no way to access the App Clip. In both scenarios, the App Clip seems to show up in the "App Clips" section of Settings.

Can anyone verify that this issue does not occur with a non-React Native App Clip on the most recent iOS versions?

**Comment by nathan-ahn** [comment]
Not elegant, but here's a workaround on iOS 18.1 to open your app clip in a simulator:

1. Find your opened simulator uuid using `xcrun simctl list`. It'll be labeled with (Booted)
2. Run `xcrun simctl launch <UUID> <APP_CLIP_BUNDLE_ID>`
    - Ex: `xcrun simctl launch 549E9898-326B-4663-8D85-041B070964BD com.bundle.app.Clip`
    
I imagine we can swap out Expo's failed command to open the app automatically with this version to open the App Clip automatically.

**Comment by nathan-ahn** [comment]
This can be fixed by running your App Clip from Xcode at least once. After that first time, your App Clip should correctly appear in the App Library section. You can then use command line builds since the App Clip will still be in the App Library section. 

If there's a use-case not covered by the above `xcrun simctl launch` workaround nor Xcode build, please open a new issue :)
