### ISSUE TITLE
Pod install fails with error: unknown command 'react-native-config'

### ISSUE THREAD

**Issue by kowczarz** [bndkt/react-native-app-clip#54]
As in description. After upgrading the package to version `0.5.0` `expo prebuild` fails on pod install stage with following error.

To get this message I had to modify [that lines](https://github.com/bndkt/react-native-app-clip/blob/main/plugin/src/withPodfile.ts#L45-L49) to following

```
  json, message, status = Pod::Executable.capture_command(config_command[0], config_command[1..], capture: :both)
  if not status.success?
    Pod::UI.warn "The command: '#{config_command.join(" ").bold.yellow}' returned a status code of #{status.exitstatus.to_s.bold.red}", [
        "App Clip autolinking failed. Please ensure autolinking works correctly for the main app target and try again.",
        "#{message}"
    ]
```

I'm on expo `51.0.18`. 

If you will need more details I can provide it.

**Comment by nathan-ahn** [comment]
Thanks for the issue report! If you're using Expo 51, please downgrade to the most recent compatible version of this package, 0.3.1. Expo 51 is no longer supported in 0.4.0 and later versions, as described in the README. I've updated the release notes for our 0.4.0 release to better describe the breaking change.
