### ISSUE TITLE
Is the resulting AppClip from a fresh Expo project really 15.4MB? Any way to reduce its size?

### ISSUE THREAD

**Issue by iuliuvisovan** [bndkt/react-native-app-clip#6]
Hey, great work on this library!

I just tried it with a fresh Expo project (as demoed in your presentation video https://www.youtube.com/watch?v=RO6tLuAitPo).

However after building it I have 2 files: 
`clipper` - 30.9MB 
`clipper Clip` - 15.4MB

Since the size limit for AppClips is 10MB (soon 15MB for iOS 16), what's the idea here? What exactly can be shaved down from the base Expo project such that it goes below the size limit?

Thanks

**Comment by bndkt** [comment]
Thanks for trying it out! There are still some improvements I need to make, hope to get back to it in the coming weeks. Regarding the size: The size of the file produced by the build is unfortunately no indication of the actual App Clip size. Please refer to the Apple Developer docs for how to determine the actual App Clip size: https://developer.apple.com/documentation/app_clips/creating_an_app_clip_with_xcode
