### ISSUE TITLE
[v0.3.1] `UIDeviceFamily` error

### ISSUE THREAD

**Issue by timmyjose** [bndkt/react-native-app-clip#60]
**App**: expo SDK 51
**SDK version**: v0.3.1

App Clip target build via `Xcode`: No errors.
Full App target build (via `XCode`): 
Error:
```
The UIDeviceFamily of an App Clip ('[1]') must be equal to the UIDeviceFamily of its containing parent app ('[1, 2]').
```

**Comment by nathan-ahn** [comment]
This issue is fixed in 0.5.0. If you're unable to upgrade due to the version minimums, you can find the fix here: 5f178f8bf19383bc8f1263847a3d23cc9bf5e882
